### ISSUE TITLE
Looking for the development

### ISSUE THREAD

**Issue by tarkonian** [rochus-keller/Micron#1]
I dreaming oberon implementation without GC.
With time you can build Concurrence and Parallel Programming since the beginning in the language design. 
I test for some time the Zonnon language and many of the features was incorporated in the A2 Oberon.
I don´t have the skill to designer a language/compiler, but i am impressed with the A2 project (the language and not the system).
You can write in the basic Oberon (serial) and the compiler:
- generate vectorizes version for arrays, loops, etc...
- generate threads (without the user need to create threats, lock, join, mutex variables, etc...)
- automatic parallel computation in multi-core

Interesting is that the compiler makes the work. 
In general (like your concurrence designer) is the programmer that have to create the parallel code. In the A2 is the compiler that create the machine code in parallel.
Similar to the Chapel language.
In Fortran we have a keyword CONCURRENCE that indicates to the compiler that the loop is to be executed in parallel, but not all the fortran compiler have this implementation (the intel compiler has). 
Congratulation for this project.

PS:The main problem (in my opinion) with the A2 implementation is that the FOX compiler only work inside the A2 System and when you compile to c, the code generated don't use only the c libraries (he generate code that will need to use, for example, kenellog.h, an A2-oberon library).  The code generated in c is useless.

**Comment by rochus-keller** [comment]
I think you're rather looking for a high-level language with abstractions optimized for mathematical and number crunching applications. Micron instead is a rather low-level language, even more minimal than Oberon+, but with more powerful features for low-level programming. I won't even add the concurrency features envisioned for Oberon+, but directly use low-level concurrency primitives instead. I will use the language e.g. to build OS kernels or embedded (microcontroller) systems. The idea is to have the power of C without (all) of its disadvantages.

**Comment by tarkonian** [comment]
For embedded the only oberon implementation that i know is from

CFB Software - Astrobe <https://astrobe.com/>

They are very active in the oberon ethz mailing list.

Good luck with your language.

PS: I also found this link GitHub - aixp/O7: Oberon → ARMv{6,7E}-M compiler
<https://github.com/aixp/O7>

Em seg., 5 de fev. de 2024 às 13:43, Rochus Keller ***@***.***>
escreveu:

**Comment by rochus-keller** [comment]
Thanks for the hint. I had a look at it some time ago. There is no solution yet like the language I'm currently implementing.
